### ISSUE TITLE
`*.import` files are missing.

### ISSUE THREAD

**Issue by Sslaxx** [Pyxus/fray#18]
`*.import` **files** _are_ necessary for assets to work correctly (e.g., filtering with sprites). The project's current `.gitignore` has those set to be ignored in it as well as (correctly) `.import`. This confusion is why projects use the `.godot` directory in Godot 4 instead.

https://github.com/Sslaxx/Godot_Sonic_Engine/blob/master/.gitignore is an example of a correct `.gitignore`.

**Comment by Pyxus** [comment]
Thank you for informing me of the distinction! I've released a patch to resolve this.
