### ISSUE TITLE
Add rollback netcode

### ISSUE THREAD

**Issue by ValorZard** [Pyxus/fray#26]
I think it would be cool if this could support rollback netcode.

The plugins for rollback in Godot haven't been updated to 4.0 yet but they do exist! See:
https://gitlab.com/snopek-games/godot-rollback-netcode
and their deterministic physics addon: https://gitlab.com/snopek-games/sg-physics-2d

**Comment by Pyxus** [comment]
@ValorZard Just wanted to inform you. I had a brief chat with snopek, developer of the rollback addon you linked, seems hes actively porting it to godot 4 as a GDExtension. I'm keeping an eye on it as making fray compatible would be more manageable than trying to run my own solution.

**Comment by Pyxus** [comment]
I'm interested in exploring rollback netcode but considering the already slow development due to my lack of time i'm going to just say it is outside the scope of this project.

**Comment by Pyxus** [comment]
I'm interested in exploring rollback netcode but considering the already slow development due to my lack of time i'm going to just say it is outside the scope of this project.
