### ISSUE TITLE
Godot hard crash due to FileSystem interaction with FrayCombatStateMachine

### ISSUE THREAD

**Issue by 20milliliter** [Pyxus/fray#28]
This is a weird one.

If there's a saved .tscn containing a FrayCombatStateMachine node that's currently open and CTRL+C is executed (despite this key combination being non-functional normally) within the FileSystem window, Godot hard crashes.

I'd be very surprised if there wasn't a larger engine bug at play here. Regardless, I wanted to check with you first. 
Can you reproduce? You happen to have the slightest clue why this is happening?

**Comment by Pyxus** [comment]
So I wasn't able to recreate the problem in the exact way you described but I did notice an issue with the combat state machine which was likely the cause. Try the most recent commit and let me know ce2d4e5bdc2926ee8de9e532ee2fba7099d0d8b9

**Comment by 20milliliter** [comment]
The issue appears to be resolved now. Thanks.
