### ISSUE TITLE
FrayCombatStateMachine doesn't display its icon in Remote SceneTree window

### ISSUE THREAD

**Issue by 20milliliter** [Pyxus/fray#50]
Title. It works fine in local but does not in remote, instead displaying the default `Node` icon.

Extremely low priority issue, of course.

**Comment by Pyxus** [comment]
Most likely a godot 4 issue but I'll look into it at some point. Thanks.

**Comment by Pyxus** [comment]
Seems to be a Godot Issue. A proposal exists but there have so far been no updates.
See: https://github.com/godotengine/godot-proposals/issues/2084
