### ISSUE TITLE
FrayCombatStateMachine documentation doesn't adequately describe how to utilize conditions

### ISSUE THREAD

**Issue by 20milliliter** [Pyxus/fray#59]
Given FrayRootState construction:
```gdscript
var hit_state = FrayRootState.builder()\
	.transition("hit_low", "recovered", {
		"auto_advance" = true, advance_conditions = [FrayCondition.new("on_recovery")]
	})\
	.transition("hit_high", "recovered", {
		"auto_advance" = true, advance_conditions = [FrayCondition.new("on_recovery")]
	})\
.build()
```

The following warning is thrown when attempting to set the condition value: 
```gdscript
combat_state_machine.get_root().set_condition("on_recovery", false)
```
> state.gd:31 @ set_condition(): Condition '%s' does not exist

**Comment by Pyxus** [comment]
Works fine on my end. Conditions are stored per state object is hit_state the same object as get_root()? Combat state machines are designed to change root states based on the current situation so perhaps not?

**Comment by Pyxus** [comment]
Fixed by https://github.com/Pyxus/fray/commit/8e25c52fb79f6b72e8022ca76f2a94d6be013b37
