### ISSUE TITLE
GitHub and Godot downloads are broken.

### ISSUE THREAD

**Issue by DrDesmondGaming** [Pyxus/fray#79]
When downloading Fray from GitHub the .zip file is only 176 B and contains nothing.

When downloading Fray from Godot it is only compatible with Godot 3.5.

Cloning is the only way of getting the current repo.

**Comment by DrDesmondGaming** [comment]
The current repo can be accessed from GitHub if the Releases page is used.

**Comment by 20milliliter** [comment]
> the .zip file is only 176 B and contains nothing
Can confirm.

> Fray from Godot ... is only compatible with ... 3.5
Correct, as the version on the Asset Library is Fray 1.0. Fray 2.0 is not finished, and so has not been uploaded to Asset Library.

**Comment by Pyxus** [comment]
Solved by https://github.com/Pyxus/fray/commit/abb64c34b0e299d4a2494e734692be3365252333
