### ISSUE TITLE
Some scripts fail to compile on load

### ISSUE THREAD

**Issue by pfinco** [Pyxus/fray#82]
I'm not sure if I'm downloading the addon files wrong but whenever I try and add Fray to my project I get the following errors:
![image](https://github.com/Pyxus/fray/assets/42593299/02bd46c8-6e4f-41d1-a916-7569ae7f5d6b)
I get the same results when being added to a new project in both Godot 4.0 and 4.2

**Comment by Pyxus** [comment]
Seems the errors only appeared on a fresh install. This should be resolved by my latest commits: https://github.com/Pyxus/fray/commit/285b4f143a7f35d0d2e98e3cc30d68173b425ebe https://github.com/Pyxus/fray/commit/3212ecabe20bcce5a30c20d14ee3477c831b19d6 https://github.com/Pyxus/fray/commit/9b32f176d2e86f4e9c4174e2e0f9ad8b8fbe6ced https://github.com/Pyxus/fray/commit/891ccd0445aa3153fd913dfffc148d1a4fa2cf6c

And just a heads-up, Fray is 4.2+ as of https://github.com/Pyxus/fray/commit/2fdf6089c88797dbc87f082800e666da1f49f250
