### ISSUE TITLE
Have you heard of the fighting game developers discord?

### ISSUE THREAD

**Issue by ValorZard** [Pyxus/fray#83]
Bit inconvenient to make this a github issue, but its probably the best way to contact you about it.
Here's the link: https://discord.gg/tfhufFqh

~~Also, are you guys aware of Snopek's Rollback Netcode framework for godot?~~

**Comment by 20milliliter** [comment]
> Also, are you guys aware of Snopek's Rollback Netcode framework for godot?

Discussed in #26.

**Comment by ValorZard** [comment]
Oh totally forgot about the fact that I mentioned that already. Woops!

**Comment by Pyxus** [comment]
> Bit inconvenient to make this a github issue, but its probably the best way to contact you about it.
> Here's the link: https://discord.gg/tfhufFqh

Nope, I wasn't aware of this server. I went ahead and joined, thanks for the invite! Also just for future reference, the discussion page is open for posts like this.
