### ISSUE TITLE
Building a State Machine documentation: Too few arguments on state_machine.state_changed.connect()

### ISSUE THREAD

**Issue by Lukaswbrr** [Pyxus/fray#84]
Given the following code on the documentation:

```gdscript
var state_machine: FrayStateMachine = $StateMachine

func _ready() -> void:
    state_machine.state_changed.connect()

func _process():
    if Input.is_action_just_pressed("ui_select"):
        state_machine.advance()

func _on_StateMachine_state_changed(from: StringName, to: StringName) -> void:
    print("State transitioned from '%s' to '%s'" % [from, to])

```

I receive the following error:

> Too few arguments for "connect()" call. Expected at least 1 but received 0.

I also noticed receiving a error on _process() function for not having _delta argument and print_adj() for being a nonexistent function

**Comment by Pyxus** [comment]
Thank you for reporting this oversight.

Fixed by https://github.com/Pyxus/fray/commit/e5ab4f82b796bdba67ce940dafe9b6abc77e9028

Also a few more documentation improvements were made in https://github.com/Pyxus/fray/commit/e965e50dfa2490f8f543d3191eec3deecfc40b1e
